name: Release do projeto utilizando Kubernetes na Google Cloud

on:
  workflow_call:

env:
  # full docker image name without version
  IMAGE_NAME_MS_ASSOCIADOS: leoalmeida/ms-associados
  IMAGE_NAME_MS_PAUTAS: leoalmeida/ms-pautas
  IMAGE_NAME_MS_SESSOES: leoalmeida/ms-sessoes
  IMAGE_NAME_API_GATEWAY: leoalmeida/api-gateway
  IMAGE_NAME_SERVICE_DISCOVERY: leoalmeida/service-discovery


jobs:
  release-associados:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
        java-distribution: [temurin]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Get current version
      id: get_version
      run: echo "::set-output name=current_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

    - name: Build Spring Boot Docker image and push it
      run: |
        mvn --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME_MS_ASSOCIADOS:${{ steps.get_version.outputs.current_version }}
        gcloud auth configure-docker leoalmeida --quiet
        docker push $IMAGE_NAME_MS_ASSOCIADOS:${{ steps.get_version.outputs.current_version }}

    - name: Bump version
      run: |
        NEXT_VERSION=$((${{ steps.get_version.outputs.current_version }} + 1))
        mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false

    - name: Commit version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Release: ${{ steps.get_version.outputs.current_version }}"
        git push origin main

    # Don't forget to auth before applying
    - name: Deploy to k8s
      working-directory: deployment
      run: |
        sed -i "s|{{IMAGE_TAG}}|${{ steps.get_version.outputs.current_version }}|g" prod/deployment.yaml
        kubectl apply -f deployment.yaml

  release-pautas:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
        java-distribution: [temurin]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Get current version
      id: get_version
      run: echo "::set-output name=current_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
    - name: Build Spring Boot Docker image and push it
      run: |
        mvn --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME_MS_PAUTAS:${{ steps.get_version.outputs.current_version }}
        gcloud auth configure-docker leoalmeida --quiet
        docker push $IMAGE_NAME_MS_PAUTAS:${{ steps.get_version.outputs.current_version }} 
    - name: Bump version
      run: |
        NEXT_VERSION=$((${{ steps.get_version.outputs.current_version }} + 1))
        mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false
    - name: Commit version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Release: ${{ steps.get_version.outputs.current_version }}"
        git push origin main 
    # Don't forget to auth before applying
    - name: Deploy to k8s
      working-directory: deployment
      run: |
        sed -i "s|{{IMAGE_TAG}}|${{ steps.get_version.outputs.current_version }}|g" prod/deployment.yaml
        kubectl apply -f deployment.yaml

  release-sessoes:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
        java-distribution: [temurin]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Get current version
      id: get_version
      run: echo "::set-output name=current_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
    - name: Build Spring Boot Docker image and push it
      run: |
        mvn --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME_MS_SESSOES:${{ steps.get_version.outputs.current_version }}
        gcloud auth configure-docker leoalmeida --quiet
        docker push $IMAGE_NAME_MS_SESSOES:${{ steps.get_version.outputs.current_version }} 
    - name: Bump version
      run: |
        NEXT_VERSION=$((${{ steps.get_version.outputs.current_version }} + 1))
        mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false
    - name: Commit version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Release: ${{ steps.get_version.outputs.current_version }}"
        git push origin main 
    # Don't forget to auth before applying
    - name: Deploy to k8s
      working-directory: deployment
      run: |
        sed -i "s|{{IMAGE_TAG}}|${{ steps.get_version.outputs.current_version }}|g" prod/deployment.yaml
        kubectl apply -f deployment.yaml
  
  release-api-gateway:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
        java-distribution: [temurin]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Get current version
      id: get_version
      run: echo "::set-output name=current_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
    - name: Build Spring Boot Docker image and push it
      run: |
        mvn --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME_API_GATEWAY:${{ steps.get_version.outputs.current_version }}
        gcloud auth configure-docker leoalmeida --quiet
        docker push $IMAGE_NAME_API_GATEWAY:${{ steps.get_version.outputs.current_version }} 
    - name: Bump version
      run: |
        NEXT_VERSION=$((${{ steps.get_version.outputs.current_version }} + 1))
        mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false
    - name: Commit version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Release: ${{ steps.get_version.outputs.current_version }}"
        git push origin main 
    # Don't forget to auth before applying
    - name: Deploy to k8s
      working-directory: deployment
      run: |
        sed -i "s|{{IMAGE_TAG}}|${{ steps.get_version.outputs.current_version }}|g" prod/deployment.yaml
        kubectl apply -f deployment.yaml
  release-service-discovery:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [17]
        java-distribution: [temurin]
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ matrix.java-distribution }}
    - name: Get current version
      id: get_version
      run: echo "::set-output name=current_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
    - name: Build Spring Boot Docker image and push it
      run: |
        mvn --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME_SERVICE_DISCOVERY:${{ steps.get_version.outputs.current_version }}
        gcloud auth configure-docker leoalmeida --quiet
        docker push $IMAGE_NAME_SERVICE_DISCOVERY:${{ steps.get_version.outputs.current_version }} 
    - name: Bump version
      run: |
        NEXT_VERSION=$((${{ steps.get_version.outputs.current_version }} + 1))
        mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false
    - name: Commit version
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Release: ${{ steps.get_version.outputs.current_version }}"
        git push origin main 
    # Don't forget to auth before applying
    - name: Deploy to k8s
      working-directory: deployment
      run: |
        sed -i "s|{{IMAGE_TAG}}|${{ steps.get_version.outputs.current_version }}|g" prod/deployment.yaml
        kubectl apply -f deployment.yaml