name: Docker Hub Image

on:
  workflow_call:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set Docker Build
      uses: docker/setup-buildx-action@v3.12.0
    - name: Docker login
      uses: docker/login-action@v4.0.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWD }}
    - name: Docker push backend
      uses: docker/build-push-action@v6.19.2
      with:
        file: ./ms-associados/Dockerfile
        context: ./ms-associados
        push: true
        tags: leoalmeida/ms-associados:${{github.run_number}}
    - name: Docker push ms-pautas
      uses: docker/build-push-action@v6.19.2
      with:
        file: ./ms-pautas/Dockerfile
        context: ./ms-pautas
        push: true
        tags: leoalmeida/ms-pautas:${{github.run_number}}
    - name: Docker push ms-sessoes
      uses: docker/build-push-action@v6.19.2
      with:
        file: ./ms-sessoes/Dockerfile
        context: ./ms-sessoes
        push: true
        tags: leoalmeida/ms-sessoes:${{github.run_number}}
    - name: Docker push api-gateway
      uses: docker/build-push-action@v6.19.2
      with:
        file: ./api-gateway/Dockerfile
        context: ./api-gateway
        push: true
        tags: leoalmeida/api-gateway:${{github.run_number}} 
    - name: Docker push service-discovery
      uses: docker/build-push-action@v6.19.2
      with:
        file: ./service-discovery/Dockerfile
        context: ./service-discovery
        push: true
        tags: leoalmeida/service-discovery:${{github.run_number}}