name: ms-pautas Module - CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  code-quality-pautas:
    name: ms-pautas Module - Code Quality Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      #- name: Run spotless check
      #  run: mvn -B -f ms-pautas/pom.xml spotless:check

      - name: Run Checkstyle
        run: mvn -B -f ms-pautas/pom.xml checkstyle:check

      - name: Generate Checkstyle report
        run: mvn -B -f ms-pautas/pom.xml checkstyle:checkstyle

      - name: Run PMD check
        run: mvn -B -f ms-pautas/pom.xml pmd:check

      - name: generate PMD report
        run: mvn -B -f ms-pautas/pom.xml pmd:pmd
      
      - name: Run spotbugs check
        run: mvn -B -f ms-pautas/pom.xml spotbugs:check

      - name: Generate SpotBugs report
        run: mvn -B -f ms-pautas/pom.xml spotbugs:spotbugs
  
  test-pautas:
    needs: [code-quality-pautas]
    name: ms-pautas Module - Execute Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
  
      - name: Roda os testes do módulo ms-pautas
        run: mvn -B -f ms-pautas/pom.xml clean package
      - name: Run Code Quality Analysis do módulo ms-pautas
        run: mvn -B -f ms-pautas/pom.xml jacoco:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ms-pautas/target/site/jacoco/jacoco.xml
          flags: ms-pautas
          name: ms-pautas-coverage
          fail_ci_if_error: false
          verbose: true
      - name: Upload Coverage Report do módulo ms-pautas
        uses: actions/upload-artifact@v6
        with:
          name: ms-pautas-coverage-report
          path: ms-pautas/target/site/jacoco/
          retention-days: 1

  build-pautas:
    needs: [test-pautas]
    name: ms-pautas Module - Build and Artifact Uploads
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build ms-pautas module
        run: mvn -B -f ms-pautas/pom.xml clean package -DskipTests
      
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v6
        with:
          name: ms-pautas-jar
          path: ms-pautas/target/*.jar
          retention-days: 1

#  zap_scan:
#    runs-on: ubuntu-latest
#    name: ZAP Scan Baseline
#    env:
#      DATABASE_URL: ${{ secrets.DATABASE_URL }}
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v4
#    - name: Fazer Build da aplicação de teste
#      run: docker compose build
#    - name: Subir a aplicação de teste local
#      run: docker compose up -d
#    - name: ZAP Scan
#      uses: zaproxy/action-full-scan@v0.12.0
#      env: 
#          INSTANCE_IP: localhost
#      with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
#          target: "http://${{ env.INSTANCE_IP }}:3000"
#          cmd_options: |
#            chmod a+rwx '/zap/wrk/zap.yaml'
#          allow_issue_writing: false 
#    # Docs: https://github.com/actions/upload-artifact
#    - name: Upload Scan Report
#      uses: actions/upload-artifact@v4
#      with:
#        name: zap_report.html
#        path: .
#        retention-days: 5
  
#  ms-pautas-docker:
#    name: ms-pautas Module - Docker Build and Push
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v6
#    - name: Set Docker Build
#      uses: docker/setup-buildx-action@v3.12.0
#    - name: Docker login
#      uses: docker/login-action@v4.0.0
#      with:
#        username: ${{ secrets.DOCKER_HUB_USERNAME }}
#        password: ${{ secrets.DOCKER_HUB_PASSWD }}
#    - name: Docker push ms-pautas
#      uses: docker/build-push-action@v6.19.2
#      with:
#        file: ./ms-pautas/Dockerfile
#        context: ./ms-pautas
#        push: true
#        tags: leoalmeida/ms-pautas:${{github.run_number}}
  
#  release-ms-pautas:
#    if: github.event.pull_request.merged == true && github.base_ref == 'main'
#    name: ms-pautas Module - Release
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        java-version: [17]
#        java-distribution: [temurin]
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v6
#    - name: Set up JDK ${{ matrix.java-version }}
#      uses: actions/setup-java@v5
#      with:
#        java-version: ${{ matrix.java-version }}
#        distribution: ${{ matrix.java-distribution }}
#    - name: Get current version
#      id: get_version
#      run: echo "::set-output name=current_version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
#    - name: Build Spring Boot Docker image and push it
#      run: |
#        mvn --batch-mode spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME_MS_PAUTAS:${{ steps.get_version.outputs.current_version }}
#        gcloud auth configure-docker leoalmeida --quiet
#        docker push $IMAGE_NAME_MS_PAUTAS:${{ steps.get_version.outputs.current_version }} 
#    - name: Bump version
#      run: |
#        NEXT_VERSION=$((${{ steps.get_version.outputs.current_version }} + 1))
#        mvn versions:set -DnewVersion=$NEXT_VERSION -DgenerateBackupPoms=false
#    - name: Commit version
#      run: |
#        git config user.name "github-actions[bot]"
#        git config user.email "github-actions[bot]@users.noreply.github.com"
#        git commit -am "Release: ${{ steps.get_version.outputs.current_version }}"
#        git push origin main 
#    # Don't forget to auth before applying
#    - name: Deploy to k8s
#      working-directory: deployment
#      run: |
#        sed -i "s|{{IMAGE_TAG}}|${{ steps.get_version.outputs.current_version }}|g" prod/deployment.yaml
#        kubectl apply -f deployment.yaml
