name: CI

#on:
#  workflow_call:
on: [pull_request]

jobs:
  backend-workflow:
    uses: ./.github/workflows/workflow-backend.yml
    secrets: inherit
    
  #zap-scan:
  #  needs: build-project
  #  uses: ./.github/workflows/zapscan.yml
  #  secrets: inherit
  
  #docker:
  #  needs: zap-scan
  #  uses: ./.github/workflows/docker.yml
  #  secrets: inherit
  
  #deploy_google:
  #  needs: docker
  #  uses: ./.github/workflows/release-gcloud.yml
  #  secrets: inherit

  