name: CI Pipeline for api-gateway Module

on:
  push:
    branches:
      - main

jobs:
  code-quality-api-gateway:
    name: Lint do módulo api-gateway
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      #- name: Run spotless check
      #  run: mvn -B -f api-gateway/pom.xml spotless:check
        
      - name: Run Checkstyle
        run: mvn -B -f api-gateway/pom.xml checkstyle:check

      - name: Generate Checkstyle report
        run: mvn -B -f api-gateway/pom.xml checkstyle:checkstyle

      - name: Run PMD check
        run: mvn -B -f api-gateway/pom.xml pmd:check

      - name: generate PMD report
        run: mvn -B -f api-gateway/pom.xml pmd:pmd
      
      - name: Run spotbugs check
        run: mvn -B -f api-gateway/pom.xml spotbugs:check

      - name: Generate SpotBugs report
        run: mvn -B -f api-gateway/pom.xml spotbugs:spotbugs
  
  test-gateway:
    needs: [code-quality-api-gateway]
    name: Execute Unit tests for Backend Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
  
      - name: Roda os testes do módulo api-gateway
        run: mvn -B -f api-gateway/pom.xml clean package
      - name: Run Code Quality Analysis do módulo api-gateway
        run: mvn -B -f api-gateway/pom.xml jacoco:report
      - name: Upload Coverage Report do módulo api-gateway
        uses: actions/upload-artifact@v6
        with:
          name: coverage-report
          path: api-gateway/target/site/jacoco/
          retention-days: 1

  build-gateway:
    needs: [test-gateway]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build api-gateway module
        run: mvn -B -f api-gateway/pom.xml clean package -DskipTests
      
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v6
        with:
          name: api-gateway-jar
          path: api-gateway/target/*.jar
          retention-days: 1

#zap-scan:
  #  needs: build-project
  #  uses: ./.github/workflows/zapscan.yml
  #  secrets: inherit
  
  #docker:
  #  needs: zap-scan
  #  uses: ./.github/workflows/docker.yml
  #  secrets: inherit
  
  #deploy_google:
  #  needs: docker
  #  uses: ./.github/workflows/release-gcloud.yml
  #  secrets: inherit